<div class="grow basis-full xl:basis-[270px] max-w-full basis:max-w-[270px] w-full bg-blue-300 rounded-md">
    <ul class="flex flex-row flex-wrap xl:flex-col p-5 xl:p-10 gap-2.5 xl:gap-5 items-stretch">
        <li><a href="{{ route('user.dashboard') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 w-full text-center">Dashboard</a></li>
        <li><a href="{{ route('my.team.view') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-rose-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-rose-700 focus:outline-none focus:ring-2 focus:ring-rose-500 focus:ring-offset-2 w-full text-center">My Team</a></li>
        <li><a href="{{ route('transfer.page') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-blue-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-rose-700 focus:outline-none focus:ring-2 focus:ring-rose-500 focus:ring-offset-2 w-full text-center">Balance Transfer</a></li>
        <li><a href="{{ route('user.show.change.password') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-lime-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-lime-700 focus:outline-none focus:ring-2 focus:ring-lime-500 focus:ring-offset-2 w-full text-center">Change Password</a></li>
        <li><a href="{{ route('user.referral.list.view') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-gray-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-lime-900 focus:outline-none focus:ring-2 focus:ring-lime-700 focus:ring-offset-2 w-full text-center">Referrals</a></li>
        <li><a href="{{ route('user.purchase.product') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-violet-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-offset-2 w-full text-center">Purchase</a></li>
        <li><a href="{{ route('incentive.view') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-orange-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-violet-700 focus:outline-none focus:ring-2 focus:ring-violet-500 focus:ring-offset-2 w-full text-center">Incentive</a></li>
        <li><a href="{{ route('user.deposit') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-pink-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-pink-700 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:ring-offset-2 w-full text-center">Deposit</a></li>
        <li><a href="{{ route('withdraw.list') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-red-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-pink-700 focus:outline-none focus:ring-2 focus:ring-pink-500 focus:ring-offset-2 w-full text-center">Withwraw</a></li>
        <li><a href="{{ route('user.balance.transfer') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-sky-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-sky-700 focus:outline-none focus:ring-2 focus:ring-sky-500 focus:ring-offset-2 w-full text-center">Transactions</a></li>
        <li><a href="{{ route('user.invoice') }}" class="inline-flex items-center justify-center h-full rounded-md border border-transparent bg-teal-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-500 focus:ring-offset-2 w-full text-center">Invoice</a></li>
    </ul>
</div>
